# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 628)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.verticalWidget_2)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.current_submission_label = QtWidgets.QLabel(self.verticalFrame)
        self.current_submission_label.setObjectName("current_submission_label")
        self.verticalLayout.addWidget(self.current_submission_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_view = QtWidgets.QListWidget(self.verticalFrame)
        self.file_view.setObjectName("file_view")
        self.horizontalLayout_2.addWidget(self.file_view)
        self.frame = QtWidgets.QFrame(self.verticalFrame)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.compare_button = QtWidgets.QPushButton(self.frame)
        self.compare_button.setObjectName("compare_button")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.compare_button)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.requirements_view = QtWidgets.QTableView(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requirements_view.sizePolicy().hasHeightForWidth())
        self.requirements_view.setSizePolicy(sizePolicy)
        self.requirements_view.setObjectName("requirements_view")
        self.horizontalLayout.addWidget(self.requirements_view)
        self.verticalFrame1 = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame1.sizePolicy().hasHeightForWidth())
        self.verticalFrame1.setSizePolicy(sizePolicy)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.formLayout = QtWidgets.QFormLayout(self.verticalFrame1)
        self.formLayout.setObjectName("formLayout")
        self.add_requirement_button = QtWidgets.QPushButton(self.verticalFrame1)
        self.add_requirement_button.setObjectName("add_requirement_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.add_requirement_button)
        self.remove_requirement_button = QtWidgets.QPushButton(self.verticalFrame1)
        self.remove_requirement_button.setObjectName("remove_requirement_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remove_requirement_button)
        self.horizontalLayout.addWidget(self.verticalFrame1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.verticalFrame)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previous_button = QtWidgets.QPushButton(self.groupBox_2)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_3.addWidget(self.previous_button)
        self.next_button = QtWidgets.QPushButton(self.groupBox_2)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.verticalWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.about_menu = QtWidgets.QMenu(self.menubar)
        self.about_menu.setObjectName("about_menu")
        self.plugins_menu = QtWidgets.QMenu(self.menubar)
        self.plugins_menu.setObjectName("plugins_menu")
        self.settings_menu = QtWidgets.QMenu(self.menubar)
        self.settings_menu.setObjectName("settings_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_project = QtWidgets.QAction(MainWindow)
        self.action_open_project.setObjectName("action_open_project")
        self.action_new_project = QtWidgets.QAction(MainWindow)
        self.action_new_project.setObjectName("action_new_project")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_plugin_install = QtWidgets.QAction(MainWindow)
        self.action_plugin_install.setObjectName("action_plugin_install")
        self.file_menu.addAction(self.action_open_project)
        self.file_menu.addAction(self.action_new_project)
        self.file_menu.addAction(self.action_export)
        self.file_menu.addAction(self.action_exit)
        self.plugins_menu.addAction(self.action_plugin_install)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.about_menu.menuAction())
        self.menubar.addAction(self.plugins_menu.menuAction())
        self.menubar.addAction(self.settings_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QuickGrader"))
        self.current_submission_label.setText(_translate("MainWindow", ""))
        self.compare_button.setText(_translate("MainWindow", "Compare"))
        self.add_requirement_button.setText(_translate("MainWindow", "Add"))
        self.remove_requirement_button.setText(_translate("MainWindow", "Remove"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Toolbar"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.about_menu.setTitle(_translate("MainWindow", "About"))
        self.plugins_menu.setTitle(_translate("MainWindow", "Plugins"))
        self.settings_menu.setTitle(_translate("MainWindow", "Settings"))
        self.action_open_project.setText(_translate("MainWindow", "Open Project"))
        self.action_new_project.setText(_translate("MainWindow", "New Project"))
        self.action_export.setText(_translate("MainWindow", "Export"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_plugin_install.setText(_translate("MainWindow", "Install"))

